# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mclip < Formula
  desc "Clipboard sync between Mac and ArchLinux"
  homepage "https://github.com/thismixer/MultiClip"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_darwin_amd64.tar.gz"
      sha256 "6bf92066c6b66d0c833ae254cdbf731ff313d750715bc924e2514b36df8abc18"

      def install
        bin.install "mclip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_darwin_arm64.tar.gz"
      sha256 "54f351db26443de1cc92186540373040a72b53c42eec22fe9689f5adf2f9771b"

      def install
        bin.install "mclip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_linux_amd64.tar.gz"
      sha256 "aa220e3ddae8118771fde9cf3b9af71f2aed8676797c0ac7525305d696a90cde"
      def install
        bin.install "mclip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_linux_arm64.tar.gz"
      sha256 "5c47a157009937137a6050ce94d5d48eedd2744a7091d8287499809bf9f0ad51"
      def install
        bin.install "mclip"
      end
    end
  end
end
