# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mclip < Formula
  desc "Clipboard sync between Mac and ArchLinux"
  homepage "https://github.com/thismixer/MultiClip"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_darwin_amd64.tar.gz"
      sha256 "be790c187e4c11f98f8dcf8b65a10a4743d94fc9ab2e8ff63ef855bcb67ac80a"

      def install
        bin.install "mclip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_darwin_arm64.tar.gz"
      sha256 "a0a2df6396988c4a7157a8b322c87aeeeb574d991b5f2b0f804096224fa33e9f"

      def install
        bin.install "mclip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_linux_amd64.tar.gz"
      sha256 "e146ed4bf111c8b02c549d7f94490aac6527e57926e5c1814470f28494e10da0"
      def install
        bin.install "mclip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_linux_arm64.tar.gz"
      sha256 "72db38d3785cda36a19a3c5ff943d2a4c80541873e35d990517f5d6cd81d5360"
      def install
        bin.install "mclip"
      end
    end
  end
end
