# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mclip < Formula
  desc "Clipboard sync between Mac and ArchLinux"
  homepage "https://github.com/thismixer/MultiClip"
  version "1.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_darwin_amd64.tar.gz"
      sha256 "b4ee0a08419923ec19b9aea8611f48cf1f4677b52b191811623208509dbd567a"

      def install
        bin.install "mclip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_darwin_arm64.tar.gz"
      sha256 "4e6f25f9a75c927daa25eeb5211ad3dafc591d5fe745d2120be6fe9f6ae85859"

      def install
        bin.install "mclip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_linux_amd64.tar.gz"
      sha256 "66310eb748c2c398feff92b795e82b51a2a2690f361b37dee2524459f52a8e0d"
      def install
        bin.install "mclip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.5/mclip_linux_arm64.tar.gz"
      sha256 "8bc287aa9b58d6390bb8e8ae9c0b35d3a0fc185afc70ad03d688f99c87376821"
      def install
        bin.install "mclip"
      end
    end
  end
end
