# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mclip < Formula
  desc "Clipboard sync between Mac and Arch"
  homepage "https://github.com/thismixer/MultiClip"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.1/mclip_darwin_amd64.tar.gz"
      sha256 "e703a5a711a13ade7e7809b64447d2e464de23882b6065817962a5c01937afc2"

      def install
        bin.install "mclip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.1/mclip_darwin_arm64.tar.gz"
      sha256 "cb41bcab47ded75b3a72929f52c5268ed24536a74b807f5b16455cd609edb8ef"

      def install
        bin.install "mclip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.1/mclip_linux_amd64.tar.gz"
      sha256 "0a211fda849844bd720399e099a79d0c5e6fa5eebeaf3202b6f79ecb48c9b673"
      def install
        bin.install "mclip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thismixer/MultiClip/releases/download/v1.0.1/mclip_linux_arm64.tar.gz"
      sha256 "7216f038a2fee14cf4cba8d42a5ca1dbfcbc10ecc740ad33a69d56198f562e77"
      def install
        bin.install "mclip"
      end
    end
  end
end
